GET http://localhost:4000/comment

###

GET http://localhost:4000/comment/5NwlxPHSKlRBLvOVwn2g7i

###
POST http://localhost:4000/comment
content-type: application/json

{
    "text": "Example text",
	"userId": 2,
	"trackId": "5NwlxPHSKlRBLvOVwn2g7i",
	"trackName": "test",
	"artistName": "example artist",
	"albumImage": "example album Image"
}